apiVersion: v1
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
stringData:
  VAULT_ADDR: http://192.168.1.7:8200
  VAULT_TOKEN: "token"
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
