apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-kustomize
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: avp-kustomization/overlays/dev
    repoURL: https://gitlab.com/deniz.turkmen/argocd-example.git
    targetRevision: main