apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev
namePrefix: dev-
# nameSuffix: "-001"

images:
  - name: nginx
    newName: nginx
    newTag: latest

secretGenerator:
  - name: my-secret
    files:
      - secret-file.txt
    envs:
      - secret-env-file.env

# This setup ensures that the secrets are generated correctly from the specified files and environment variables. 
# The disableNameSuffixHash option is used to prevent Kustomize from adding a hash suffix to the secret name, 
# which is useful if you need a predictable name for the secret.
generatorOptions:
  disableNameSuffixHash: true