apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-

resources:
- ../../base

secretGenerator:
- name: more-secret
  literals:
  - KEY1=newsecretvalue1
  - KEY2=newsecretvalue2
  - KEY3=anothersecretvalue