##################################################
# Zookeeper Persistent Volume
##################################################
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zookeeper-pv
  labels:
    app: zookeeper
  namespace: kafkacluster
spec:
  hostPath:
    path: "/home/deniz/volume/zookeeper"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-master-1
---
##################################################
# Zookeeper Persistent Volume Claims
##################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pv-claim-0
  namespace: kafkacluster
  labels:
    app: zookeeper
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  selector:
    matchLabels:
      app: zookeeper
---