##################################################
# Kafka Persistent Volume
##################################################
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv
  labels:
    app: kafka
  namespace: kafkacluster
spec:
  hostPath:
    path: "/home/deniz/volume/kafka"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-master-1
---
##################################################
# Kafka Persistent Volume Claims
##################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-release-0
  namespace: kafkacluster
  labels:
    app: kafka
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  selector:
    matchLabels:
      app: kafka
---
