---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-test-k8s-cm
data:
  myvalue: "Hello World"
  drink: dendsadsadsadssadsasd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader-poc-ubuntu-deployment
  labels:
    app: ubuntu
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep", "123456"]
        env:
        - name: DRINK
          valueFrom:
            configMapKeyRef:
              name: my-test-k8s-cm
              key: drink
        - name: MYVALUE
          valueFrom:
            configMapKeyRef:
              name: my-test-k8s-cm
              key: myvalue